apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: mogle
  labels:
    service: mogle
spec:
  claimRef:
    name: postgres-pvc
    namespace: mogle
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ebs-csi-sc
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-0edbcee8b7002ca4a