{{- if .Values.application.backend }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  name: "{{ .Release.Name }}-backend-network-policy"
  namespace: "{{ .Release.Namespace }}"
spec:
  podSelector:
    matchLabels:
      app: "{{ .Release.Name }}-backend"
  policyTypes:
    - Ingress
  ingress:
  {{- if .Values.application.frontend }}
  - from:
      - podSelector:
          matchLabels:
            app: "{{ .Release.Name }}-frontend"
        namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: "{{ .Chart.Name }}"
    {{- end }}
{{- end }}