{{- if .Values.application.frontend }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  name: "{{ .Release.Name }}-frontend-network-policy"
  namespace: "{{ .Release.Namespace }}"
spec:
  podSelector:
    matchLabels:
      app: "{{ .Release.Name }}-frontend"
  policyTypes:
    - Ingress
  ingress:
  - from:
      - ipBlock:
          cidr: 192.168.0.0/16
{{- end }}