{{- if .Values.pvc.frontend }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  name: "{{ .Release.Name }}-frontend-pvc"
  namespace: "{{ .Release.Namespace }}"
spec:
  selector:
    matchLables:
      app: "{{ .Release.Name }}-deployment-frontend"
  accessModes:
    - ReadWriteMany
  storageClassName: "efs-sc"
  resources:
    requests:
      storage: "{{ .Values.pvc.frontend.storage }}"
{{- end }}