{{ if .Values.service.backend }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  name: "{{ .Release.Name }}-backend-svc"
  namespace: "{{ .Release.Namespace }}"
spec:
  ports:
    - port: {{ .Values.service.backend.port }}
      protocol: TCP
      name: http
      targetPort: {{ .Values.application.backend.port }}
  selector:
    app: "{{ .Release.Name }}-backend"
{{ end }}