apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mogle-backend-pvc
  namespace: mogle
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi

