apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-nginx
  namespace: default
spec:
  project: default
  source:
    repoURL: https://42cluster-seoul.github.io/helm-charts/stable
    chart: demo-nginx
    targetRevision: 0.1.0
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
