apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-nginx
  namespace: argocd
spec:
  project: default
  source:
    path: stable/demo-nginx
    repoURL: https://github.com/42Cluster-Seoul/helm-charts.git
    targetRevision: HEAD
    helm:
      valueFiles:
      - $values/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
