apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-hpa-no-rollout
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.slack-42cluster-argocd: ""
spec:
  project: default
  source:
    path: stable/demo-hpa-no-rollout
    repoURL: https://github.com/42Cluster-Seoul/helm-charts
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
