apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-hpa
  namespace: argocd
spec:
  project: demo-project
  source:
    path: stable/demo-hpa
    repoURL: https://github.com/42Cluster-Seoul/helm-charts
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}
