apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: morning-glory
  namespace: argocd
spec:
  project: default
  source:
    path: stable/morning-glory
    repoURL: https://github.com/42Cluster-Seoul/helm-charts
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: mogle
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
