apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-umbrella
  namespace: argocd
spec:
  project: default
  source:
    path: stable/open-umbrella-s3
    repoURL: https://github.com/42Cluster-Seoul/helm-charts
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: openumbrella
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
