apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring
  namespace: spring
spec:
  project: default
  source:
    path: stable/spring
    repoURL: https://github.com/42Cluster-Seoul/helm-charts
    targetRevision: seongtki
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: spring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true