app:
  name: "demo-hpa"
  image: "registry.k8s.io/hpa-example"
  port: 80
  minReplicas: 1
  maxReplicas: 4
  averageUtilization: 30
  resources:
    requests:
      cpu: "1m"
      memory: "128Mi"
    limits:
      cpu: "1m"
      memory: "128Mi"

podAnnotations: {}
podLabels:
  tier: backend

service:
  enabled: true
  port: 80
