app:
  name: "demo-hpa"
  image: "argoproj/rollouts-demo:green22"
  port: 80
  minReplicas: 1
  maxReplicas: 4
  averageUtilization: 30
  resources:
    requests:
      cpu: "200m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "128Mi"

podAnnotations: {}
podLabels:
  tier: backend

service:
  enabled: true
  port: 80
