{{- if and (.Values.hpa.backend) (eq .Values.deployment.strategy "Rolling") }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/component: backend
  name: "{{ .Release.name }}-backend-hpa"
  namespace: "{{ .Release.Namespace }}"
spec:
  minReplicas: {{ .Values.hpa.backend.replicas.min }}
  maxReplicas: {{ .Values.hpa.backend.replicas.max }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "{{ .Release.Name }}-deployment-backend"
  {{- with .Values.hpa.backend.metrics  }}
  metrics:
    {{- toYaml .Values.hpa.backend.metrics | nindent 4 }}
  {{- end }}
{{- end }}