apiVersion: v1
kind: PersistentVolume
metadata:
  name: mogle-frontend-pv
spec:
  claimRef:
    name: mogle-frontend-pvc
    namespace: mogle
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: "fs-0c82ec6c9881e78aa:fsap-0e5a23e3123854dc7"

