{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.app.frontend.name }}
  name: {{ .Values.app.frontend.name }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    name: http
    targetPort: {{ .Values.app.frontend.port }}
  selector:
    app: {{ .Values.app.frontend.name }}
{{- end }}