app:
  name: "spring"
  replicas: 1
  image: "738612635754.dkr.ecr.ap-northeast-2.amazonaws.com/stecr:latest"
  port: 80
  resources: 
    requests:
      cpu: "1m"
      memory: "128Mi"
    limits:
      cpu: "1m"
      memory: "128Mi"

podAnnotations: {}
podLabels:
  tier: backend

ingress:
  enabled: false
  className: alb
  host: ""
  path: /
  pathType: Prefix

service:
  enabled: true
  port: 80