app:
  name: "demo-hpa-no-rollout"
  image: "nginx:stable-alpine3.19-perl22"
  port: 80
  minReplicas: 1
  maxReplicas: 4
  averageUtilization: 30
  resources:
    requests:
      cpu: "200m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "128Mi"

podAnnotations: {}
podLabels:
  tier: backend

service:
  enabled: true
  port: 80
