apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.backend.name }}
  labels:
    app: {{ .Values.app.backend.name }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: {{ .Values.app.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.backend.name }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Values.app.backend.name }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - image: {{ .Values.app.backend.image }}
        name: {{ .Values.app.backend.name }}
        {{- with .Values.app.backend.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        ports:
          - name: http
            protocol: TCP
            containerPort: {{ .Values.app.backend.port }}