app:
  name: "demo-nginx"
  replicas: 3
  image: "giafar/nginx:1.25.1-tcpdump"
  port: 80
  resources:
    requests:
      cpu: "1m"
      memory: "128Mi"
    limits:
      cpu: "1m"
      memory: "128Mi"

podAnnotations: {}
podLabels:
  tier: backend

service:
  enabled: true
  port: 80
